name: Promote
run-name: Promote
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: 'recursive'
    
      - name: Install dependency
        run: sudo apt-get update && sudo apt-get -y install build-essential cmake ninja-build libeigen3-dev libpng-dev libjemalloc-dev

      - name: Install boost library
        uses: MarkusJx/install-boost@v2.4.4
        id: install-boost
        with:
            boost_version: 1.83.0
            platform_version: 22.04
            boost_install_dir: /home/runner/boost_1_83_0
      
      - name: Check boost library
        run: ls -al /home/runner/boost_1_83_0/boost/boost/lib

      - name: Build nanoHEAT
        run: export BOOST_PATH=/home/runner/boost_1_83_0/boost/boost && cmake -Bbuild -DNS_MALLOC_LIB=jemalloc -DENABLE_ASSERTION=ON -DENABLE_EXCEPTION=ON -DENABLE_ASAN=ON -G Ninja && cmake --build build

      - name: Run unit test
        run: build/bin/nanoTest.exe
        
      - name: Create pull request
        if: success()
        run: gh pr create -B main -H dev --title 'Merge dev into main' --body 'created by github action'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}